# Generated by Django 5.2.8 on 2025-12-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_invoice_discount_amount_invoice_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='event_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Event End Date'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='event_location',
            field=models.CharField(blank=True, max_length=500, verbose_name='Event Location'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='event_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Event Start Date'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='event_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Event End Date'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='event_location',
            field=models.CharField(blank=True, max_length=500, verbose_name='Event Location'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='event_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Event Start Date'),
        ),
    ]
