# Generated by Django 5.2.8 on 2025-12-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_invoice_event_end_date_invoice_event_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='quotation',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
