# Generated by Django 5.2.8 on 2026-04-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_quotation_discount_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quotationitem',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
